### ISSUE TITLE
bug: hitting while blocking

### ISSUE THREAD

**Issue by Oguzhan5585** [Tee-6/Auto_Attack#4]
with the mod you can still hit while blocking with a shield. this is impossible in vanilla, which basically makes it a cheat.

i think there is 2 ways to fix this:
1. prevent hitting while blocking
or
2. if the player tries to hit while blocking, put the shield down, attack, and then put the shield back up again. (basically as if the player let go of the right mouse button to attack and then held it down again to continue blocking)

**Comment by Tee-6** [comment]
@Oguzhan5585  Thanks for bringing this to my attention. I'll take a look whenever I have time.

**Comment by Tee-6** [comment]
Finally got around to fixing it. It should be fixed in V3
