### ISSUE TITLE
some questions with the mod

### ISSUE THREAD

**Issue by SonThanhVN** [Tee-6/Auto_Attack#5]
while in third person, i dont see the arm of character moving
and while using some anticheat will flag as Killaura

**Comment by Tee-6** [comment]
Thanks for letting me know. I don't have time to work on it right now, so in the meantime, I've labeled the mod as a "Cheat" on the Modrinth page.

**Comment by Tee-6** [comment]
> while in third person, i dont see the arm of character moving and while using some anticheat will flag as Killaura

This should be fixed with v2. Thanks for reporting it
